[package]
name = "math-and-algorithm"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
itertools = "0.10.3"
proconio = "0.4.3"
text_io = "0.1.10"
whiteread = "0.5.0"

[profile.release]
lto = true
panic = 'abort'
